spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@ync2023-japan-class-cteam.cxoxbdpjlvzo.ap-northeast-2.rds.amazonaws.com:1521:PROJECT
    username: message_function
    password: pw4
  jpa:
    show-sql: true
    database: oracle
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

